export const SET_POKEMON_TYPES = 'SET_POKEMON_TYPES';
export const SET_POKEMONS_BY_TYPE = 'SET_POKEMONS_BY_TYPE';
export const SET_POKEMON_DETAILS = 'SET_POKEMON_BY_DETAILS';
export const CATCH_POKEMON = 'CATCH_POKEMON';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';
export const SAVE_SELECTED_POKEMON_TYPE = 'SAVE_SELECTED_POKEMON_TYPE';

export const FETCH_POKEMON_TYPES_LOADING = 'FETCH_POKEMON_TYPES_LOADING';
export const FETCH_POKEMONS_BY_TYPE_LOADING = 'FETCH_POKEMONS_BY_TYPE_LOADING';
export const FETCH_POKEMON_DETAILS_BY_NAME_LOADING = 'FETCH_POKEMON_DETAILS_BY_NAME_LOADING';
